name: 🚀 Deploy production
on:
  release:
    types:
      - released

jobs:
  build-deploy-production:
    name: 🛠️ Build & 🚀 Deploy production
    runs-on: ubuntu-latest
    environment: production
    env:
      RUNTIME_CONFIG_NETATMO_JSON: ${{ secrets.RUNTIME_CONFIG_NETATMO_JSON }}
      RUNTIME_CONFIG_COLLECTIONS_JSON: ${{ secrets.RUNTIME_CONFIG_COLLECTIONS_PROD_JSON }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
      - run: npx nx run-many --target=runtime-config
      - run: npx nx run-many --target=build
      - run: npx nx run-many --target=deploy -- --prod --message \"Version ${{ github.ref_name }}\"
